name: Run a smoke test (CI)

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
        with:
          persist-credentials: false

      - name: Install Go
        uses: action/setup-go@v3
        with: 
          go-version-file: go.mod

      - name: Fech required Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... 